package edu.tum.cs.crawling.facebook.entities;

public class SmallPost extends Post {

	private static final long serialVersionUID = 8761457817658149615L;

	private final SmallPostHeader header;
	private final String text;

	public SmallPost(SmallPostHeader header, String text) {
		this.header = header;
		this.text = text;
	}

	public SmallPostHeader getHeader() {
		return header;
	}

	/** SmallPosts without texts were usually generated by apps (FarmVille, Flickr, etc.) */
	@Override
	public String getText() {
		return text;
	}

}
